prefix: '&f[&6OGN&f]'
chat:
  format: '{prefix}{name}&r %tag% &7>> {message-color}{message}'
afk:
  timeout-seconds: 300
tab-list:
  header:
  - '&f&lOakGlow'
  - ''
  footer:
  - ''
  - '&fOnline for: &a%sessiontime%'
rtp:
  world: world
  min-radius: 500
  max-radius: 1500
  max-attempts: 20
  confirm-timeout-seconds: 60
  excluded-biomes:
  - OCEAN
  - DEEP_OCEAN
  - COLD_OCEAN
  - DEEP_COLD_OCEAN
  - FROZEN_OCEAN
  - DEEP_FROZEN_OCEAN
  - LUKEWARM_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - WARM_OCEAN
chat-notifications:
  enabled: true
  interval-seconds: 1200
  messages:
  - '&aJoin our Discord: &fhttps://discord.com/invite/vSajqg6ChK'
  - '&aVisit our website: &fhttps://OakGlow.net'
  - '&aStuck in someones claim? You can do &f/stuck &ato get out!'
  - '&aTired of system messages like this? You can do &f/settings &aand disable them!'
starting-balance: 100.0
storage:
  type: txt
  mysql:
    enabled: true
    upload-balances: true
    upload-event: true
    host: localhost
    port: 3306
    database: oakglown_ogu
    username: oakglown_ogu
    password: okay
    use-ssl: false
    connect-timeout-ms: 5000
    socket-timeout-ms: 5000
    log-connection-tests: false
hug:
  enabled: true
  heart_count: 15
  cooldown: 15
event:
  enabled: false
  acceptedblocks:
  - STONE
  - COBBLESTONE
  - DEEPSLATE
  - COBBLED_DEEPSLATE
spawn:
  enabled: true
  world: world
  x: 638.4964369377686
  y: 85.0
  z: 581.5107662546019
  yaw: 0.4650885
  pitch: 4.1999288
dragon-drops:
  enabled: true
  drop-elytra: true
  drop-egg: true
  drop-head: true
  location:
    world: world
    x: 0.0
    y: 65.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
